const http=require('http'),fs=require('fs'),path=require('path');
const PORT=Number(process.env.PORT||3000),PUBLIC=path.join(__dirname,'public');
const crypto=require('crypto');
const TWITCH_CLIENT_ID=process.env.TWITCH_CLIENT_ID||'cc5te66gm5qmewa3pz1cfuqhcfx28i';
const TWITCH_CLIENT_SECRET=process.env.TWITCH_CLIENT_SECRET||'';
const TWITCH_REDIRECT_URI=process.env.TWITCH_REDIRECT_URI||'https://landmark-duel.onrender.com/auth/twitch/callback';
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{let i=x.indexOf('=');return [decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}))}
function cookie(n,v,o=''){return `${n}=${encodeURIComponent(v)}; Path=/; SameSite=Lax; ${o}`}
function redir(res,url,headers={}){res.writeHead(302,{Location:url,...headers});res.end()}

const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8'};
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');
 if(u.pathname==='/auth/twitch'){const st=crypto.randomBytes(20).toString('hex');let ret=String(u.searchParams.get('return')||'/');if(!ret.startsWith('/')||ret.startsWith('//'))ret='/';const q=new URLSearchParams({client_id:TWITCH_CLIENT_ID,redirect_uri:TWITCH_REDIRECT_URI,response_type:'code',scope:'user:read:email',state:st});return redir(res,'https://id.twitch.tv/oauth2/authorize?'+q,{'Set-Cookie':[cookie('ld_state',st,'HttpOnly; Secure; Max-Age=600'),cookie('ld_return',ret,'HttpOnly; Secure; Max-Age=600')]})}
 if(u.pathname==='/auth/twitch/callback'){try{const c=cookies(req),st=u.searchParams.get('state')||'',code=u.searchParams.get('code')||'';if(!code||!st||st!==c.ld_state)throw Error('Invalid Twitch login');if(!TWITCH_CLIENT_SECRET)throw Error('TWITCH_CLIENT_SECRET missing');const body=new URLSearchParams({client_id:TWITCH_CLIENT_ID,client_secret:TWITCH_CLIENT_SECRET,code,grant_type:'authorization_code',redirect_uri:TWITCH_REDIRECT_URI});const r=await fetch('https://id.twitch.tv/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw Error('Twitch token '+r.status);const j=await r.json();let ret=String(c.ld_return||'/');if(!ret.startsWith('/')||ret.startsWith('//'))ret='/';return redir(res,ret,{'Set-Cookie':[cookie('ld_token',j.access_token,'HttpOnly; Secure; Max-Age='+Math.max(300,+j.expires_in||3600)),cookie('ld_state','','HttpOnly; Secure; Max-Age=0'),cookie('ld_return','','HttpOnly; Secure; Max-Age=0')]})}catch(e){return redir(res,'/?twitch_error='+encodeURIComponent(e.message))}}
 if(u.pathname==='/api/twitch/me'){const tok=cookies(req).ld_token;if(!tok){res.writeHead(401,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:false}))}try{const r=await fetch('https://api.twitch.tv/helix/users',{headers:{Authorization:'Bearer '+tok,'Client-Id':TWITCH_CLIENT_ID}});if(!r.ok)throw Error('Twitch user '+r.status);const j=await r.json(),x=j.data&&j.data[0];if(!x)throw Error('No Twitch user');res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,user:{id:x.id,login:x.login,displayName:x.display_name,avatar:x.profile_image_url}}))}catch(e){res.writeHead(401,{'Content-Type':'application/json','Cache-Control':'no-store','Set-Cookie':cookie('ld_token','','HttpOnly; Secure; Max-Age=0')});return res.end(JSON.stringify({ok:false}))}}
 if(u.pathname==='/health'||u.pathname==='/api/health'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,mode:'geo-duel-v20.9-stable-p2p-twitch',rooms:'browser-p2p'}));}
 if(u.pathname==='/api/pano'){try{const raw=String(u.searchParams.get('url')||''),x=new URL(raw),h=x.hostname.toLowerCase();if(!(h.endsWith('openstreetcam.org')||h.endsWith('kartaview.org')))throw Error('blocked');const c=new AbortController(),t=setTimeout(()=>c.abort(),15000),r=await fetch(x,{headers:{'User-Agent':'LandmarkDuel/20.3'},signal:c.signal});clearTimeout(t);if(!r.ok)throw Error('HTTP '+r.status);const b=Buffer.from(await r.arrayBuffer());res.writeHead(200,{'Content-Type':r.headers.get('content-type')||'image/jpeg','Cache-Control':'public,max-age=3600'});return res.end(b)}catch(e){res.writeHead(502);return res.end('Panorama unavailable')}}
 let f=u.pathname==='/'?path.join(PUBLIC,'index.html'):path.join(PUBLIC,u.pathname.replace(/^\//,''));if(!f.startsWith(PUBLIC))return res.writeHead(403).end();fs.stat(f,(e,st)=>{if(e||!st.isFile()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(f).pipe(res)})});
server.listen(PORT,()=>console.log('Landmark Duel V20.9 STABLE on '+PORT));
