const http=require('http'),fs=require('fs'),path=require('path');
const PORT=Number(process.env.PORT||3000),PUBLIC=path.join(__dirname,'public'),locations=require('./locations.json');
const TWITCH_CLIENT_ID=process.env.TWITCH_CLIENT_ID||'cc5te66gm5qmewa3pz1cfuqhcfx28i';
const TWITCH_CLIENT_SECRET=process.env.TWITCH_CLIENT_SECRET||'';
const TWITCH_REDIRECT_URI=process.env.TWITCH_REDIRECT_URI||'https://landmark-duel.onrender.com/auth/twitch/callback';
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{let i=x.indexOf('=');return [decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}))}
function cookie(name,value,opts=''){return `${name}=${encodeURIComponent(value)}; Path=/; SameSite=Lax; ${opts}`}
function redirect(res,url,headers={}){res.writeHead(302,{Location:url,...headers});res.end()}
function randomState(){return require('crypto').randomBytes(20).toString('hex')}

const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8'};
const FALL={lat:-6.193911,lng:106.849350,heading:150.16,url:'https://storage13.openstreetcam.org/files/photo/2022/10/6/wrapped_proc/6187609_626b8_633f5d392b4be.jpg',country:'Indonesia',countryCode:'ID'};
const countryMap={paris:['France','FR'],london:['United Kingdom','GB'],rome:['Italy','IT'],barcelona:['Spain','ES'],'new-york':['United States','US'],'san-francisco':['United States','US'],toronto:['Canada','CA'],rio:['Brazil','BR'],'buenos-aires':['Argentina','AR'],sydney:['Australia','AU'],melbourne:['Australia','AU'],tokyo:['Japan','JP'],kyoto:['Japan','JP'],osaka:['Japan','JP'],singapore:['Singapore','SG'],bangkok:['Thailand','TH'],'kuala-lumpur':['Malaysia','MY'],dubai:['United Arab Emirates','AE'],istanbul:['Türkiye','TR'],athens:['Greece','GR'],berlin:['Germany','DE'],amsterdam:['Netherlands','NL'],brussels:['Belgium','BE'],vienna:['Austria','AT'],prague:['Czechia','CZ'],budapest:['Hungary','HU'],sofia:['Bulgaria','BG'],lisbon:['Portugal','PT'],madrid:['Spain','ES'],copenhagen:['Denmark','DK'],stockholm:['Sweden','SE'],oslo:['Norway','NO'],helsinki:['Finland','FI'],reykjavik:['Iceland','IS'],'cape-town':['South Africa','ZA'],johannesburg:['South Africa','ZA'],nairobi:['Kenya','KE'],'mexico-city':['Mexico','MX'],'los-angeles':['United States','US'],chicago:['United States','US'],washington:['United States','US'],seoul:['South Korea','KR'],taipei:['Taiwan','TW'],'hong-kong':['Hong Kong','HK'],auckland:['New Zealand','NZ'],wellington:['New Zealand','NZ'],dublin:['Ireland','IE'],edinburgh:['United Kingdom','GB'],zurich:['Switzerland','CH'],munich:['Germany','DE']};
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function extractPhotos(j){let pools=[j?.result?.data,j?.result?.photos,j?.data,j?.photos,j?.result];for(let x of pools)if(Array.isArray(x))return x;return []}
function photoUrl(p){return p.fileurlProc||p.fileurl||p.procUrl||p.url||p.imageUrl||''}
async function nearby(loc){let u=`https://api.openstreetcam.org/2.0/photo/?lat=${encodeURIComponent(loc.lat)}&lng=${encodeURIComponent(loc.lng)}&zoomLevel=12`;let c=new AbortController(),t=setTimeout(()=>c.abort(),7000);try{let r=await fetch(u,{headers:{'User-Agent':'LandmarkDuel/20.6'},signal:c.signal});if(!r.ok)return null;let j=await r.json(),ps=extractPhotos(j).filter(p=>photoUrl(p)&&((+p.fieldOfView||0)>=300||String(p.projection||'').toUpperCase().includes('SPHERE')));if(!ps.length)return null;let p=ps[Math.floor(Math.random()*ps.length)],cc=countryMap[loc.id]||[loc.name,''];return{lat:+p.lat||loc.lat,lng:+p.lng||loc.lng,heading:+p.heading||0,url:photoUrl(p),country:cc[0],countryCode:cc[1]}}catch{return null}finally{clearTimeout(t)}}
async function buildRounds(n){let out=[],used=new Set();for(let loc of shuffle(locations)){if(out.length>=n)break;let p=await nearby(loc);if(p&&!used.has(p.url)){used.add(p.url);out.push(p)}}if(out.length<Math.min(n,5)){try{for(let page of shuffle([1,2,3,4,5,6,7,8]).slice(0,4)){let r=await fetch(`https://api.openstreetcam.org/2.0/photo/?sequenceId=6187609&page=${page}&itemsPerPage=150`,{headers:{'User-Agent':'LandmarkDuel/20.6'}});if(!r.ok)continue;let ps=extractPhotos(await r.json()).filter(p=>photoUrl(p)&&((+p.fieldOfView||0)>=300||String(p.projection||'').toUpperCase().includes('SPHERE')));for(let p of shuffle(ps)){if(out.length>=n)break;if(used.has(photoUrl(p)))continue;used.add(photoUrl(p));out.push({lat:+p.lat||FALL.lat,lng:+p.lng||FALL.lng,heading:+p.heading||0,url:photoUrl(p),country:'Indonesia',countryCode:'ID'})}}}catch{}}
 if(!out.length)out.push(FALL);return out}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');
 if(u.pathname==='/auth/twitch'){let st=randomState();let q=new URLSearchParams({client_id:TWITCH_CLIENT_ID,redirect_uri:TWITCH_REDIRECT_URI,response_type:'code',scope:'openid user:read:email',state:st,force_verify:'true'});return redirect(res,'https://id.twitch.tv/oauth2/authorize?'+q.toString(),{'Set-Cookie':cookie('ld_tw_state',st,'HttpOnly; Secure; Max-Age=600')})}
 if(u.pathname==='/auth/twitch/callback'){try{let c=cookies(req),state=u.searchParams.get('state')||'',code=u.searchParams.get('code')||'';if(!code||!state||state!==c.ld_tw_state)throw Error('Invalid Twitch login state');if(!TWITCH_CLIENT_SECRET)throw Error('TWITCH_CLIENT_SECRET is missing on Render');let body=new URLSearchParams({client_id:TWITCH_CLIENT_ID,client_secret:TWITCH_CLIENT_SECRET,code,grant_type:'authorization_code',redirect_uri:TWITCH_REDIRECT_URI});let tr=await fetch('https://id.twitch.tv/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!tr.ok)throw Error('Twitch token HTTP '+tr.status);let tj=await tr.json();return redirect(res,'/?twitch=ok',{'Set-Cookie':[cookie('ld_tw_token',tj.access_token,'HttpOnly; Secure; Max-Age='+Math.max(300,Number(tj.expires_in||3600))),cookie('ld_tw_state','','HttpOnly; Secure; Max-Age=0')]})}catch(e){return redirect(res,'/?twitch_error='+encodeURIComponent(e.message))}}
 if(u.pathname==='/auth/twitch/logout'){return redirect(res,'/',{'Set-Cookie':cookie('ld_tw_token','','HttpOnly; Secure; Max-Age=0')})}
 if(u.pathname==='/api/twitch/me'){let tok=cookies(req).ld_tw_token;if(!tok){res.writeHead(401,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:false}))}try{let r=await fetch('https://api.twitch.tv/helix/users',{headers:{'Authorization':'Bearer '+tok,'Client-Id':TWITCH_CLIENT_ID}});if(!r.ok)throw Error('Twitch user HTTP '+r.status);let j=await r.json(),x=j.data&&j.data[0];if(!x)throw Error('No Twitch user');res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,user:{id:x.id,login:x.login,displayName:x.display_name,avatar:x.profile_image_url}}))}catch(e){res.writeHead(401,{'Content-Type':'application/json','Cache-Control':'no-store','Set-Cookie':cookie('ld_tw_token','','HttpOnly; Secure; Max-Age=0')});return res.end(JSON.stringify({ok:false,error:e.message}))}}
 if(u.pathname==='/health'||u.pathname==='/api/health'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,mode:'geo-duel-v20.6-twitch',rooms:'browser-p2p',twitch:!!TWITCH_CLIENT_SECRET}))}
 if(u.pathname==='/api/rounds'){let n=Math.max(1,Math.min(25,Number(u.searchParams.get('count')||25)));let rounds=await buildRounds(n);res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({rounds,count:rounds.length}))}
 if(u.pathname==='/api/pano'){try{const raw=String(u.searchParams.get('url')||''),x=new URL(raw),h=x.hostname.toLowerCase();if(!(h.endsWith('openstreetcam.org')||h.endsWith('kartaview.org')))throw Error('blocked');const c=new AbortController(),t=setTimeout(()=>c.abort(),15000),r=await fetch(x,{headers:{'User-Agent':'LandmarkDuel/20.6'},signal:c.signal});clearTimeout(t);if(!r.ok)throw Error('HTTP '+r.status);const b=Buffer.from(await r.arrayBuffer());res.writeHead(200,{'Content-Type':r.headers.get('content-type')||'image/jpeg','Cache-Control':'public,max-age=3600'});return res.end(b)}catch(e){res.writeHead(502);return res.end('Panorama unavailable')}}
 let f=u.pathname==='/'?path.join(PUBLIC,'index.html'):path.join(PUBLIC,u.pathname.replace(/^\//,''));if(!f.startsWith(PUBLIC))return res.writeHead(403).end();fs.stat(f,(e,st)=>{if(e||!st.isFile()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(f).pipe(res)})});
server.listen(PORT,()=>console.log('Landmark Duel V20.5 on '+PORT));
